baseurl: ""
title: "Bug Bounty Village "
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Bug Bounty Village"
  Description: "Bug Bounty Village"
  Date: "March 3, 4 & 5, 2019"
  Venue: "International Centre Goa"
  City:  "Goa"
  # Images: ["/img/badge.jpg"]
  #GoogleMapsKey: "my-secret-maps-key"


  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - cfr
    - cftw
    - awards
    - speakers
    - review
    - teams
    - schedule
    - sponsors
    - location
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    schedule: "Schedule"
    location: "Location"
    cfr: "Call for Nominations"
    cftw: "Call for Talks/ Workshops" 
#    ctf: "CTF"
    awards: "Awards"
    speakers: "Speakers"
    teams: "Team"
    review: "Review Committee"
#     schedule: "CTF"
    sponsors: "Sponsors"
#    partners: "Partners"
    #contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  # CallToAction:
  #   text: "Call for Speakers"
  #   link: "https://docs.google.com/forms/d/1L6r-h9_ENMnx9Auzaj7JteVQOuNQrPZ-4FSlJEk_xSY"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "OwaspSeasides"
      logo: "/img/OWASP-final.png"
      url: "https://www.owaspseasides.com"
    - name: "PentesterLab"
      logo: "/img/pentesterlab.png"
      url: "https://pentesterlab.com/"
    - name: "Hak5"
      logo: "/img/images.png"
      url: "https://shop.hak5.org/"


  #  - name: "hak5"
  #    logo: "/img/os.png"
  #    url: "https://shop.hak5.org/"

  # The entire schedule
  Schedule:
    - name: ""
      time: ""
    
  Teams:
    - name: "Praveen Yadav"
      logo: "/img/praveenyadav.jpg"
      linkdinUrl: "https://www.linkedin.com/in/parveen1015/"
      twitterUrl: "https://twitter.com/parveen1015"
  
    - name: "Prashant K V"
      logo: "/img/prashantkv.jpg"
      linkdinUrl: "https://www.linkedin.com/in/prashant-venkatesh-99018999"
      twitterUrl: "https://twitter.com/goodbestguy"

    - name: "Narendra Kumar"
      logo: "/img/Narendra.jpeg"
      linkdinUrl: "https://www.linkedin.com/in/narendra-k-0981b7104/"
      twitterUrl: "https://twitter.com/0ddhawk"
    
    - name: "Pankaj Upadhyay"
      logo: "/img/pankaj_upadhyay.jpg"
      linkdinUrl: "https://www.linkedin.com/in/p4nk4j/"
      twitterUrl: "https://twitter.com/lazyhack3r"

  Speakers:
    - name: "Nimisha Dugalya"
      photo: "/img/a4.jpg"
      bio: "The workshop is hands-on white-box testing of a php-based application. Most of the server-side web applications are made up of Php, this workshop will introduce the attendees to some common vulnerabilities in php applications. This session will be a ctf based session where the related challenges will be hosted and the participants who are well ahead of the basic topics can solve them while others catch up. Topics that will be covered in this session are - common php coding mistakes, code reviewing for loopholes, server-side request forgery, deserialization vulnerability.
After the session participants will have a clear understanding of how to analyze a web application for php bugs."
      presentation:
        title: "Exploiting Server-Side Applications"
      # link:
      #   href: "http://twitter.com/linus"
      #   text: "@linus"

    - name: "Amol Naik"
      photo: "/img/a2.jpg"
      bio: "This course focus on findings & exploiting bugs in leading browsers. This hands-on training will help participants to develop their own fuzzers.
The course also covers domain of the fuzzing, frameworks and analysing the crashes. Bugs like Use-After-Free & Heap Corruptions/Overflow will be
discussed as case study with in-depth analysis using debuggers."
      presentation:
        title: "XTREME BROWSER FUZZING"
      # link:
      #   href: "http://twitter.com/linus"
      #   text: "@linus"

    - name: "Shikhar Joshi"
      photo: "/img/a1.jpg"
      bio: " What to expect in the session:

Overview of Docker (demo):

- Creating a docker image user dockerfile
- Uploading the docker image to docker hub
- Creating a container from the image
- Getting a shell within the container
- Linux namespace

Overview of kubernetes architecture (theory/demo if time persists)

- API Server
- etcd
- Controller
  - Scheduler
- Kubelet
- Nodes

Creation of kubernetes resources (demo)

- pods
- namespaces
- replication controllers/sets
- services
- roles

Exploiting kubernetes cluster (demo)

- Understanding authentication and authorisation in kubernetes cluster
- Understanding kubernetes secrets
- Exploiting the cluster via misconfigured RBAC
- Exploiting the cluster via exposed resources"
      presentation:
        title: "Kubernetes - Overview and Exploitation"
      # link:
      #   href: "http://twitter.com/linus"
      #   text: "@linus"




    # - name: "Praveen Yadav"
    #   logo: "/img/praveenyadav.jpg"
    #   linkdinUrl: "https://www.linkedin.com/in/parveen1015/"
    #   twitterUrl: "https://twitter.com/parveen1015"
    #   bio: "Security Researcher"
    # - name: "Prashant K V"
    #   logo: "/img/prashantkv.jpg"
    #   bio: "Security Researcher"
    #   linkdinUrl: "https://www.linkedin.com/in/prashant-venkatesh-99018999"
    #   twitterUrl: "https://twitter.com/goodbestguy"

    # - name: "Vandana Verma"
    #   logo: "/img/vandanaverma.jpg"
    #   url: "https://www.linkedin.com/in/vandana-verma/"
    #   bio: "lorem10"
    # - name: "Jason Haddix"
    #   logo: "/img/jasonhaddix.jpg"
    #   url: "https://www.linkedin.com/in/jhaddix/"
    #   bio: "lorem10"
    # - name: "Jason Haddix"
    #   logo: "/img/jasonhaddix.jpg"
    #   url: "https://www.linkedin.com/in/jhaddix/"
    #   bio: "lorem10"
    # - name: "Jason Haddix"
    #   logo: "/img/jasonhaddix.jpg"
    #   url: "https://www.linkedin.com/in/jhaddix/"
    #   bio: "lorem10"
  Review:
    - name: "Eduardo Vela"
      bio: "Google"
      logo: "/img/speaker1.jpg"
      twitterUrl: "https://twitter.com/sirdarckcat"
    - name: "Pranav Hivarekar"
      logo: "/img/pran.jpeg"
      twitterUrl: "https://twitter.com/HivarekarPranav"
      linkdinUrl: "https://www.linkedin.com/in/pranavhivarekar/"
    - name: "Nikhil Srivastava"
      logo: "/img/nikhil.JPG"
      twitterUrl: "https://twitter.com/niksthehacker"
      linkdinUrl: "https://www.linkedin.com/in/nikhilksrivastava/"