baseurl: ""
title: "Bug Bounty Village "
canonifyurls: true
theme: "hugo-conference"

googleAnalytics: ""


params:
  # Conference info
  Name: "Bug Bounty Village"
  Description: "Bug Bounty Village"
  Date: "March 3, 4 & 5, 2019"
  Venue: "International Centre Goa"
  City:  "Goa"
  # Images: ["/img/badge.jpg"]
  #GoogleMapsKey: "my-secret-maps-key"


  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - cfr
    - cftw
    - awards
    
    - speakers
    - review
    - teams
    - schedule
    - sponsors
    - location
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    schedule: "Schedule"
    location: "Location"
    cfr: "Call for Nominations"
    cftw: "Call for Talks/ Workshops" 
#    ctf: "CTF"
    awards: "Awards"
    speakers: "Speakers"
    teams: "Team"
    review: "Review Committee"
#     schedule: "CTF"
    sponsors: "Sponsors"
#    partners: "Partners"
    #contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  # CallToAction:
  #   text: "Call for Speakers"
  #   link: "https://docs.google.com/forms/d/1L6r-h9_ENMnx9Auzaj7JteVQOuNQrPZ-4FSlJEk_xSY"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "OwaspSeasides"
      logo: "/img/OWASP-final.png"
      url: "https://www.owaspseasides.com"
    - name: "PentesterLab"
      logo: "/img/pentesterlab.png"
      url: "https://pentesterlab.com/"
    - name: "Hak5"
      logo: "/img/images.png"
      url: "https://shop.hak5.org/"


  #  - name: "hak5"
  #    logo: "/img/os.png"
  #    url: "https://shop.hak5.org/"

  # The entire schedule
  Schedule:
    - name: ""
      time: ""
    
  Teams:
    - name: "Praveen Yadav"
      logo: "/img/praveenyadav.jpg"
      linkdinUrl: "https://www.linkedin.com/in/parveen1015/"
      twitterUrl: "https://twitter.com/parveen1015"
  
    - name: "Prashant K V"
      logo: "/img/prashantkv.jpg"
      linkdinUrl: "https://www.linkedin.com/in/prashant-venkatesh-99018999"
      twitterUrl: "https://twitter.com/goodbestguy"

    - name: "Narendra Kumar"
      logo: "/img/Narendra.jpeg"
      linkdinUrl: "https://www.linkedin.com/in/narendra-k-0981b7104/"
      twitterUrl: "https://twitter.com/0ddhawk"
    
    - name: "Pankaj Upadhyay"
      logo: "/img/pankaj_upadhyay.jpg"
      linkdinUrl: "https://www.linkedin.com/in/p4nk4j/"
      twitterUrl: "https://twitter.com/lazyhack3r"

  Speakers:
    - name: "Martin Straka"
      photo: "/img/straka.jpg"
      bio: "Martin will cover the Google VRP programs, some interesting facts and new things added this year to our VRP programs and also the best bugs Google received from our researchers community in the last year."
      registerLink: "https://docs.google.com/forms/d/1yD7ernsDlRfBp6LbH1dBofVqBxw02LnMcKRbJ_R1t8A/"
      registerLinkname: "Register"
      presentation:
        title: "Google VRP BugHunting"
      # link:
      #   href: "http://twitter.com/linus"
      #   text: "@linus"
    - name: "Andrea"
      photo: "/img/IMG_20200211_005857.png"
      bio: "
The 0day vulnerability market developed over the years in a way that is unsafe, chaotic and rather inefficient. Bad business practices, lack of professionalism and low levels of trust are still spread in this market even today and can seriously hamper the ability of law enforcement and intelligence agencies to acquire and maintain strategic cyber capabilities in order to fight organized crime, terrorism and hostile geopolitical actors. 

Having a deep understanding of these issues and of their solutions, Crowdfense is “hacking the 0day market” in order to improve it for all the parties involved (researchers, customers, brokers, integrators and end users), by introducing new quality standards and best practices related to products, services and to the sustainability of the underlying business processes. 

This session will share how Crowdfense is doing this, why, what are the results, some statistics about the 0day market and what could be the next steps."
      # registerLink: "https://docs.google.com/forms/d/1yD7ernsDlRfBp6LbH1dBofVqBxw02LnMcKRbJ_R1t8A/"
      # registerLinkname: "Register"
      presentation:
        title: "Hacking the 0day Market"

    - name: "Nimisha Dugalya"
      photo: "/img/Nimisha.JPG"
      bio: "The workshop is hands-on white-box testing of a php-based application. Most of the server-side web applications are made up of Php, this workshop will introduce the attendees to some common vulnerabilities in php applications. This session will be a ctf based session where the related challenges will be hosted and the participants who are well ahead of the basic topics can solve them while others catch up. Topics that will be covered in this session are - common php coding mistakes, code reviewing for loopholes, server-side request forgery, deserialization vulnerability.
After the session participants will have a clear understanding of how to analyze a web application for php bugs."
      registerLink: "https://docs.google.com/forms/d/1Q2dFAYr9L-l7NmOKrkMBGEdjFlIULjxvObIRnM4eoRY/"
      registerLinkname: "Register"
      presentation:
        title: "Exploiting Server-Side Applications"
      # link:
      #   href: "http://twitter.com/linus"
      #   text: "@linus"

    - name: "Amol Naik"
      photo: "/img/Amol-Naik1.jpg"
      bio: "This workshop focuses on the fuzzing softwares for bugs which will cover various techniques, tools & analysis techniques starting from file fuzzers till browser fuzzing."
      presentation:
        title: "Fuzzing softwares for Bugs"
      # link:
      #   href: "http://twitter.com/linus"
      #   text: "@linus"

    - name: "Shikhar Joshi"
      photo: "/img/Shikhar_Joshi (1).jpg"
      bio: " What to expect in the session:

Overview of Docker (demo):

- Creating a docker image user dockerfile
- Uploading the docker image to docker hub
- Creating a container from the image
- Getting a shell within the container
- Linux namespace

Overview of kubernetes architecture (theory/demo if time persists)

- API Server
- etcd
- Controller
  - Scheduler
- Kubelet
- Nodes

Creation of kubernetes resources (demo)

- pods
- namespaces
- replication controllers/sets
- services
- roles

Exploiting kubernetes cluster (demo)

- Understanding authentication and authorisation in kubernetes cluster
- Understanding kubernetes secrets
- Exploiting the cluster via misconfigured RBAC
- Exploiting the cluster via exposed resources"

      registerLink: "https://docs.google.com/forms/d/14c6sFqRakrorbf3LCb5OkF8jUN77Ri153gqalUESuYM/"
      registerLinkname: "Register"
      presentation:
        title: "Kubernetes - Overview and Exploitation"
      # link:
      #   href: "http://twitter.com/linus"
      #   text: "@linus"
    - name: "Dhamotharan"
      photo: "/img/dhamu.jpeg"
      bio: "Pre-authentication arbitrary file read vulnerability (CVE-2019-11510) that revealed sensitive information like VPN client credentials, private SSH keys, and session cookies. They showed how this information was used to compromise a client session and gain access to a VPN network, then demonstrated additional post-authentication exploits that resulted in complete takeover of the VPN server. In order to exploit the issue, an attacker can send a malicious HTTP request containing directory traversal sequences along with a crafted Uniform Resource Identifier (URI) and access any file on the device.	"
      registerLink: "https://docs.google.com/forms/d/1GmfBrK_UkqArJAu2U1acgVbceRWUIuzO2NwmfDNqEGI/"
      registerLinkname: "Register"
      presentation:
        title: "Decoding Multiple Vulnerabilities on Pulse Secure VPN?"

    - name: "Shrutirupa Banerjiee"
      photo: "/img/Shrutirupa.JPG"
      bio: "Bug bounty is one of the common platform for security researchers to learn and earn more. There are researchers out there who sometimes miss certain domains and cryptography is one such domain which should never be forgotten. The session will talk about the basics of cryptography that a bug bounty hunter has to focus on to find cryptography related flaws. The audience will learn about how a simple cryptography flaw, once ignored, can be manipulated into a vulnerability. The audience will also get to know some common cryptography based exploits to achieve bounties. Meanwhile, the audience will also learn about different vulnerabilities and their exploitations with the help of some exercises that will be provided to them along with the explanation of each vulnerability. Some of the vulnerabilities which will be covered are: JWT misconfigurations openssl based flaws Oracle Padding cbc-ecb mode weak ssl ciphers Heartbleed and many more... The targeted audience is someone who has some basic knowledge in web application security along with having some enthusiasm to learn something different."
      registerLink: "https://docs.google.com/forms/d/1djD0QzFLYZa52tztDNcYr0b-bg2QNz81YKQznh5ZRtQ/"
      registerLinkname: "Register"
      presentation:
        title: "Crypto for Bounty Hunters"





    # - name: "Praveen Yadav"
    #   logo: "/img/praveenyadav.jpg"
    #   linkdinUrl: "https://www.linkedin.com/in/parveen1015/"
    #   twitterUrl: "https://twitter.com/parveen1015"
    #   bio: "Security Researcher"
    # - name: "Prashant K V"
    #   logo: "/img/prashantkv.jpg"
    #   bio: "Security Researcher"
    #   linkdinUrl: "https://www.linkedin.com/in/prashant-venkatesh-99018999"
    #   twitterUrl: "https://twitter.com/goodbestguy"

    # - name: "Vandana Verma"
    #   logo: "/img/vandanaverma.jpg"
    #   url: "https://www.linkedin.com/in/vandana-verma/"
    #   bio: "lorem10"
    # - name: "Jason Haddix"
    #   logo: "/img/jasonhaddix.jpg"
    #   url: "https://www.linkedin.com/in/jhaddix/"
    #   bio: "lorem10"
    # - name: "Jason Haddix"
    #   logo: "/img/jasonhaddix.jpg"
    #   url: "https://www.linkedin.com/in/jhaddix/"
    #   bio: "lorem10"
    # - name: "Jason Haddix"
    #   logo: "/img/jasonhaddix.jpg"
    #   url: "https://www.linkedin.com/in/jhaddix/"
    #   bio: "lorem10"
  Review:
    - name: "Eduardo Vela"
      bio: "Google"
      logo: "/img/speaker1.jpg"
      twitterUrl: "https://twitter.com/sirdarckcat"
    - name: "Laurie Mercer"
      bio: "HackerOne"
      logo: "/img/uXDMmoc7_400x400.jpg"
      twitterUrl: "https://twitter.com/MonkeyBanking"


    - name: "Pranav Hivarekar"
      logo: "/img/pran.jpeg"
      twitterUrl: "https://twitter.com/HivarekarPranav"
      linkdinUrl: "https://www.linkedin.com/in/pranavhivarekar/"
    - name: "Nikhil Srivastava"
      logo: "/img/nikhil.JPG"
      twitterUrl: "https://twitter.com/niksthehacker"
      linkdinUrl: "https://www.linkedin.com/in/nikhilksrivastava/"