baseurl: ""
title: "Bug Bounty Village "
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Bug Bounty Village"
  Description: "Bug Bounty Village"
  Date: "March 3, 4 & 5, 2019"
  Venue: "International Centre Goa"
  City:  "Goa"
  # Images: ["/img/badge.jpg"]
  #GoogleMapsKey: "my-secret-maps-key"


  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - cfr
    - cftw
    - awards
    - speakers
    - review
    - teams
    - schedule
    - sponsors
    - location
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    schedule: "Schedule"
    location: "Location"
    cfr: "Call for Nominations"
    cftw: "Call for Talks/ Workshops" 
#    ctf: "CTF"
    awards: "Awards"
    speakers: "Speakers"
    teams: "Team"
    review: "Review Committee"
#     schedule: "CTF"
    sponsors: "Sponsors"
#    partners: "Partners"
    #contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  # CallToAction:
  #   text: "Call for Speakers"
  #   link: "https://docs.google.com/forms/d/1L6r-h9_ENMnx9Auzaj7JteVQOuNQrPZ-4FSlJEk_xSY"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "OwaspSeasides"
      logo: "/img/OWASP-final.png"
      url: "https://www.owaspseasides.com"
    - name: "PentesterLab"
      logo: "/img/pentesterlab.png"
      url: "https://pentesterlab.com/"
    - name: "Hak5"
      logo: "/img/images.png"
      url: "https://shop.hak5.org/"


  #  - name: "hak5"
  #    logo: "/img/os.png"
  #    url: "https://shop.hak5.org/"

  # The entire schedule
  Schedule:
    - name: ""
      time: ""
    
  Teams:
    - name: "Praveen Yadav"
      logo: "/img/praveenyadav.jpg"
      linkdinUrl: "https://www.linkedin.com/in/parveen1015/"
      twitterUrl: "https://twitter.com/parveen1015"
  
    - name: "Prashant K V"
      logo: "/img/prashantkv.jpg"
      linkdinUrl: "https://www.linkedin.com/in/prashant-venkatesh-99018999"
      twitterUrl: "https://twitter.com/goodbestguy"

    - name: "Narendra Kumar"
      logo: "/img/Narendra.jpeg"
      linkdinUrl: "https://www.linkedin.com/in/narendra-k-0981b7104/"
      twitterUrl: "https://twitter.com/0ddhawk"
    
    - name: "Pankaj Upadhyay"
      logo: "/img/pankaj_upadhyay.jpg"
      linkdinUrl: "https://www.linkedin.com/in/p4nk4j/"
      twitterUrl: "https://twitter.com/lazyhack3r"

  Speakers:


    - name: "Praveen Yadav"
      logo: "/img/praveenyadav.jpg"
      linkdinUrl: "https://www.linkedin.com/in/parveen1015/"
      twitterUrl: "https://twitter.com/parveen1015"
      bio: "Security Researcher"
    # - name: "Prashant K V"
    #   logo: "/img/prashantkv.jpg"
    #   bio: "Security Researcher"
    #   linkdinUrl: "https://www.linkedin.com/in/prashant-venkatesh-99018999"
    #   twitterUrl: "https://twitter.com/goodbestguy"

    # - name: "Vandana Verma"
    #   logo: "/img/vandanaverma.jpg"
    #   url: "https://www.linkedin.com/in/vandana-verma/"
    #   bio: "lorem10"
    # - name: "Jason Haddix"
    #   logo: "/img/jasonhaddix.jpg"
    #   url: "https://www.linkedin.com/in/jhaddix/"
    #   bio: "lorem10"
    # - name: "Jason Haddix"
    #   logo: "/img/jasonhaddix.jpg"
    #   url: "https://www.linkedin.com/in/jhaddix/"
    #   bio: "lorem10"
    # - name: "Jason Haddix"
    #   logo: "/img/jasonhaddix.jpg"
    #   url: "https://www.linkedin.com/in/jhaddix/"
    #   bio: "lorem10"
  Review:
    - name: "Eduardo Vela"
      logo: "/img/speaker1.jpg"
      twitterUrl: "https://twitter.com/sirdarckcat"